const products = [
    {
        type: 'men-sneakers',
        image: '/images/product_p1.jpg',
        company: 'Roadster',
        product: 'The Lifestyle Co Men White Sneakers',
        rating: 3.5,
        sp: 872,
        mrp: 3795,
        discount: 77,
        desc: {
            details: "A pair of round-toe white sneakers, has regular styling, lace-up detail",
            material: "Canvas material. Wipe with a clean, dry cloth to remove dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "EVA",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sneakers',
        image: '/images/product_p55.jpg',
        company: 'Trendigo',
        product: 'Classic Sneakers For Men ( Green )',
        rating: 4.5,
        sp: 699,
        mrp: 1699,
        discount: 59,
        desc: {
            details: "A pair of round-toe green sneakers, has regular styling, lace-up detail",
            material: "Canvas material. Wipe with a clean, dry cloth to remove dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "EVA",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sneakers',
        image: '/images/product_p2.png',
        company: 'U.S. Polo Assn.',
        product: 'Men Grey Clarkin Sneakers',
        rating: 4.7,
        sp: 2099,
        mrp: 2999,
        discount: 30,
        desc: {
            details: "A pair of round-toe white sneakers, has regular styling, lace-up detail",
            material: "Canvas material. Wipe with a clean, dry cloth to remove dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sneakers',
        image: '/images/product_p3.jpg',
        company: 'Roadster',
        product: 'Men Black Sneakers',
        rating: 4.7,
        sp: 872,
        mrp: 3795,
        discount: 77,
        desc: {
            details: "A pair of round-toe black sneakers, has regular styling, lace-up detail",
            material: "Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'women-sneakers',
        image: '/images/product_p12.jpg',
        company: 'Nike',
        product: 'Women Black Walking Non-Marking Shoes',
        rating: 4.5,
        sp: 3599,
        mrp: 3999,
        discount: 10,
        desc: {
            details: "A pair of black walking shoes, has regular Styling, lace-ups detail",
            material: "Upper material: PU. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-sneakers',
        image: '/images/product_p45.jpg',
        company: 'Red Tape',
        product: 'Women Black Walking Shoes',
        rating: 4.2,
        sp: 1199,
        mrp: 1999,
        discount: 60,
        desc: {
            details: "A pair of black walking shoes, has regular Styling, lace-ups detail",
            material: "Textile Upper. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months"
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p4.png',
        company: 'Provogue',
        product: 'Men Tan Brown Solid Formal Loafers',
        rating: 4.2,
        sp: 879,
        mrp: 4395,
        discount: 80,
        desc: {
            details: "A pair of tan brown round-toed formal loafers, has regular styling",
            material: "Synthetic leather. Allow your pair of shoes to air and de-odorize at regular basis. Use shoe bags to prevent any stains or mildew. Dust any dry dirt from the surface using a clean cloth. Do not use polish or shiner",
            specsType: "Loafers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p5.jpg',
        company: 'U.S. Polo Assn.',
        product: 'U S Polo Assn Men Navy Blue PU Loafers',
        rating: 3.9,
        sp: 2239,
        mrp: 3199,
        discount: 30,
        desc: {
            details: "A pair of square toe navy blue ,has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p6.jpg',
        company: 'HIGHLANDER',
        product: 'Men Solid Leather Loafers',
        rating: 3.9,
        sp: 1094,
        mrp: 1990,
        discount: 45,
        desc: {
            details: "A pair of square toe leather loafers, has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "PVC",
            specsWarranty: "4 months",
        }
    },
    {
        type: 'women-loafers',
        image: '/images/product_p82.jpg',
        company: 'HIGHLANDER',
        product: 'Women Solid Leather Loafers',
        rating: 3.7,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of square toe leather loafers, has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "PVC",
            specsWarranty: "4 months",
        }
    },
    {
        type: 'women-loafers',
        image: '/images/product_p83.jpg',
        company: 'Bata',
        product: 'Women Black Solid Leather Loafers',
        rating: 4.2,
        sp: 872,
        mrp: 1133,
        discount: 23,
        desc: {
            details: "A pair of round toe leather loafers, has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "PVC",
            specsWarranty: "4 months",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p7.jpg',
        company: 'H&M',
        product: 'Men Brown Chelsea boots',
        rating: 4.1,
        sp: 1199,
        mrp: 3999,
        discount: 30,
        desc: {
            details: "Chelsea boots in soft imitation suede with elastic gores in the sides and a loop at the back. Linings and insoles in imitation leather and cotton canvas. Fluted soles. Heel 2.7 cm.",
            material: "100% Polyester",
            specsType: "Chelsea Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Synthetic",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p8.jpg',
        company: 'Fentacia',
        product: 'Men Brown Solid Synthetic Leather Lightweight High-Top Flat Chelsea Boots',
        rating: 4.0,
        sp: 1259,
        mrp: 5999,
        discount: 79,
        desc: {
            details: "A pair of round-toe brown flat boots, has high-top styling, slip-on detail",
            material: "Synthetic Leather. Wipe with a clean, dry cloth to remove dust",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Narrow",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p9.jpg',
        company: 'Roadster',
        product: 'Men Black Matte Rugged Chelsea Boots',
        rating: 4.1,
        sp: 1169,
        mrp: 2599,
        discount: 55,
        desc: {
            details: "A pair of round toe black matte rugged chelsea boots , has regular styling, slip-on detail",
            material: "Upper material: Synthetic Suede. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-chelsea',
        image: '/images/product_p75.jpg',
        company: 'El Paso',
        product: 'Block Heeled Chelsea Boots with Zip Closure',
        rating: 4.1,
        sp: 800,
        mrp: 3999,
        discount: 80,
        desc: {
            details: "A pair of pointed toe black block heeled chelsea boots , has regular styling, zip detail",
            material: "Upper material: Synthetic Suede. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Chelsea Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Zip",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-chelsea',
        image: '/images/product_p76.jpg',
        company: 'H&M',
        product: 'Women Chelsea Boots',
        rating: 4.4,
        sp: 1080,
        mrp: 2699,
        discount: 40,
        desc: {
            details: "Chelsea boots with elastic gores in the sides and a loop front and back. Linings in woven fabric and chunky soles that are patterned underneath. Heel 5.5 cm.",
            material: "100% Polyurethane",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-on",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'women-chelsea',
        image: '/images/product_p77.jpg',
        company: 'Roadster',
        product: 'Women Black Solid Heeled Chelsea Boots',
        rating: 4.1,
        sp: 1099,
        mrp: 4330,
        discount: 75,
        desc: {
            details: "A pair of black round toe heeled boots, has mid-top styling, closed back detail",
            material: "Synthetic Leather. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-on",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'women-chelsea',
        image: '/images/product_p78.jpg',
        company: 'VALIOSAA',
        product: 'Women Brown Solid Heeled Chelsea Boots',
        rating: 4.1,
        sp: 1650,
        mrp: 2895,
        discount: 43,
        desc: {
            details: "A pair of brown square toe heeled boots, has mid-top styling, buckle detail",
            material: "Synthetic Leather. Wipe the surface with a soft, clean and damp cloth and brush to remove dust",
            specsType: "Chelsea Boots",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Buckle Up",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "Limited Warranty",
        }
    },
    {
        type: 'men-walking',
        image: '/images/product_p10.jpeg',
        company: 'Reebok',
        product: 'Men Navy Blue Mesh Walking Non-Marking Shoes',
        rating: 4.4,
        sp: 1439,
        mrp: 4799,
        discount: 70,
        desc: {
            details: "A pair of navy blue shoes, has regular styling, slip-on detail",
            material: "Care Instruction: Wipe with a clean, dry cloth to remove the dust.",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "45 days",
        }
    },
    {
        type: 'men-walking',
        image: '/images/product_p11.jpg',
        company: 'Campus',
        product: 'Men Blue Mesh Walking Non-Marking Shoes',
        rating: 4.4,
        sp: 899,
        mrp: 999,
        discount: 10,
        desc: {
            details: "A pair of navy blue shoes, has regular styling, slip-on detail",
            material: "Care Instruction: Wipe with a clean, dry cloth to remove the dust.",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-walking',
        image: '/images/product_p44.jpg',
        company: 'Puma',
        product: 'Men Grey Walking Shoes',
        rating: 4.6,
        sp: 1559,
        mrp: 5199,
        discount: 70,
        desc: {
            details: "A pair of grey walking shoes, has regular Styling, lace-ups detail",
            material: "Textile Upper. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "EVA",
            specsWarranty: "3 months"
        }
    },
    
    {
        type: 'men-walking',
        image: '/images/product_p47.jpg',
        company: 'Nike',
        product: 'Men Black Walking Shoes',
        rating: 4.3,
        sp: 3999,
        mrp: 4999,
        discount: 20,
        desc: {
            details: "A pair of black walking shoes, has regular Styling, lace-ups detail",
            material: "Textile Upper. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p13.jpg',
        company: 'El Paso',
        product: 'Men Black Comfort Sandals',
        rating: 4.1,
        sp: 779,
        mrp: 3895,
        discount: 80,
        desc: {
            details: "A pair of black comfort sandals, synthetic leather upper with slip-on closure",
            material: "Upper material: Synthetic Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p14.jpg',
        company: 'Redtape',
        product: 'Men Black Leather Comfort Sandals',
        rating: 4.6,
        sp: 1299,
        mrp: 1999,
        discount: 35,
        desc: {
            details: "A pair of black solid perforated comfort sandals, leather upper with slip-on closure",
            material: "Leather. Use a branded leather conditioner to clean the product. Avoid washing",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months",
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p15.jpg',
        company: 'Afrojack',
        product: 'Men Black Croslite Sliders',
        rating: 4,
        sp: 499,
        mrp: 2495,
        discount: 80,
        desc: {
            details: "A pair of black solid sliders",
            material: "Upper material: Croslite. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Croslite",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'women-sandals',
        image: '/images/product_p59.jpg',
        company: 'Shezone',
        product: 'Women Beige Gladiator Sandals',
        rating: 4.1,
        sp: 699,
        mrp: 1499,
        discount: 53,
        desc: {
            details: "A pair of beige gladiator sandals",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PVC",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'women-sandals',
        image: '/images/product_p60.jpg',
        company: 'Marc Loire',
        product: 'Women Black Embroidered One Toe Flat Sandals',
        rating: 4.3,
        sp: 997,
        mrp: 1995,
        discount: 50,
        desc: {
            details: "A pair of black embroidered one-toed flats, has regular styling, no back strap detail",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "One Toe Flat Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Resin",
            specsWarranty: "Limited Warranty",
        }
    },
    {
        type: 'women-sandals',
        image: '/images/product_p61.jpg',
        company: 'Visudh',
        product: 'Women Beige Embellished Open Toe Flat Sandals',
        rating: 4.2,
        sp: 578,
        mrp: 998,
        discount: 42,
        desc: {
            details: "A pair of beige open-toed flats, has regular styling, backstrap detail",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "One Toe Flat Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "Resin",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-sandals',
        image: '/images/product_p62.jpg',
        company: 'WLYLA',
        product: 'Women White Open Toe Flat Sandals',
        rating: 4.5,
        sp: 499,
        mrp: 999,
        discount: 50,
        desc: {
            details: "A pair of white open-toed flats, has regular styling, openstrap detail",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "One Toe Flat Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "Resin",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-boats',
        image: '/images/product_p16.jpg',
        company: 'Mast & Harbour',
        product: 'Men Brown Solid Boat Shoes',
        rating: 3.9,
        sp: 1594,
        mrp: 2899,
        discount: 45,
        desc: {
            details: "A pair of round toe brown solid boat shoes has regular styling, lace-ups detail",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Boat Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-boats',
        image: '/images/product_p17.jpg',
        company: 'Mast & Harbour',
        product: 'Men Coffee Brown Solid Boat Shoes',
        rating: 3.7,
        sp: 1594,
        mrp: 2899,
        discount: 45,
        desc: {
            details: "A pair of round toe coffee brown solid boat shoes has regular styling, lace-ups detail",
            material: "Upper material: Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Boat Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-boats',
        image: '/images/product_p18.jpg',
        company: 'Nautica',
        product: 'Men Camel Brown Leather Boat Shoes',
        rating: 3.8,
        sp: 3249,
        mrp: 4999,
        discount: 35,
        desc: {
            details: "A pair of round toe camel brown boat shoes with tie-up detail ,has regular styling, slip-on detail",
            material: "Leather. Use a branded leather conditioner to clean the product. Avoid washing",
            specsType: "Boat Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-on",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-espadrilles',
        image: '/images/product_p19.jpg',
        company: 'AfroJack',
        product: 'Men Woven Design Espadrilles',
        rating: 3.8,
        sp: 674,
        mrp: 4495,
        discount: 85,
        desc: {
            details: "A pair of square toe woven espadrilles ,has regular styling, slip-on detail",
            material: "Allow your pair of shoes to air and deodorize at regular basis use shoe bags to prevent any stains or mildew dust any dry dirt from the surface using a clean cloth do not use polish or shiner",
            specsType: "Espadrilles",
            specsToe: "Square Toe",
            specsPattern: "Woven Design",
            specsFastening: "Slip-on",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-espadrilles',
        image: '/images/product_p20.jpg',
        company: 'SHENCES',
        product: 'Men Green Woven Design Espadrilles',
        rating: 3.8,
        sp: 689,
        mrp: 2299,
        discount: 70,
        desc: {
            details: "A pair of round toe green woven espadrilles ,has regular styling, slip-on detail",
            material: "Allow your pair of shoes to air and deodorize at regular basis use shoe bags to prevent any stains or mildew dust any dry dirt from the surface using a clean cloth do not use polish or shiner",
            specsType: "Espadrilles",
            specsToe: "Round Toe",
            specsPattern: "Woven Design",
            specsFastening: "Slip-on",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-espadrilles',
        image: '/images/product_p21.jpg',
        company: 'VIV',
        product: 'Men Black Perforations Espadrilles',
        rating: 3.8,
        sp: 899,
        mrp: 1999,
        discount: 55,
        desc: {
            details: "A pair of square toe black ,has regular styling, lace-ups detail",
            material: "Upper material: Synthetic Wipe with a clean, dry cloth to remove the dust",
            specsType: "Espadrilles",
            specsToe: "Square Toe",
            specsPattern: "Perforations",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-espadrilles',
        image: '/images/product_p56.jpg',
        company: 'Nautica',
        product: 'Women Navy Blue Solid Espadrilles',
        rating: 4.8,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of navy blue solid round toe espadrilles ,has regular styling, lace-ups detail",
            material: "Upper material: Synthetic Wipe with a clean, dry cloth to remove the dust",
            specsType: "Espadrilles",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-espadrilles',
        image: '/images/product_p57.jpg',
        company: 'Mast & Harbour',
        product: 'Women Off White & Green Printed Espadrilles',
        rating: 4.2,
        sp: 1154,
        mrp: 2099,
        discount: 45,
        desc: {
            details: "A pair of round toe off white, green printed espadrilles ,has regular styling, slip-on detail",
            material: "Upper material: Synthetic Wipe with a clean, dry cloth to remove the dust",
            specsType: "Espadrilles",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-espadrilles',
        image: '/images/product_p58.jpg',
        company: 'Eske',
        product: 'Women Black Solid Leather Espadrilles',
        rating: 3.9,
        sp: 3599,
        mrp: 5999,
        discount: 40,
        desc: {
            details: "A pair of round toe black solid espadrilles ,has regular styling, slip-on detail",
            material: "Upper material: Synthetic Wipe with a clean, dry cloth to remove the dust",
            specsType: "Espadrilles",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "6 months",
        }
    },
    {
        type: 'men-chukka',
        image: '/images/product_p22.jpg',
        company: 'Next',
        product: 'Men Black Solid Suede Leather Chukka Boots',
        rating: 3.9,
        sp: 2249,
        mrp: 4999,
        discount: 55,
        desc: {
            details: "A pair of black chukka boots, has lace-ups detail",
            material: "Suede leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Desert Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-chukka',
        image: '/images/product_p23.jpg',
        company: 'Carlton London',
        product: 'Men Black Solid Mid-Top Chukka Boots',
        rating: 3.9,
        sp: 3499,
        mrp: 5999,
        discount: 42,
        desc: {
            details: "A pair of round toe brown chukka boots, has mid-top styling, has lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Desert Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "15 days",
        }
    },
    {
        type: 'men-chukka',
        image: '/images/product_p24.jpg',
        company: 'Mactree',
        product: 'Men Brown Solid Mid-Top Chukka Boots',
        rating: 3.9,
        sp: 3499,
        mrp: 4999,
        discount: 55,
        desc: {
            details: "A pair of round toe black chukka boots, has mid-top styling, has lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Desert Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "15 days",
        }
    },
    {
        type: 'men-chukka',
        image: '/images/product_p25.jpg',
        company: 'LOUIS STITCH',
        product: 'Men Tan Suede Mid-Top Boots',
        rating: 3.9,
        sp: 2699,
        mrp: 8999,
        discount: 70,
        desc: {
            details: "A pair of tan round toe boots, has mid-top styling, has lace-ups detail",
            material: "Suede. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Desert Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-brogues',
        image: '/images/product_p26.jpg',
        company: 'SHENCES',
        product: 'Men Tan Brown Leather Brogue Boots',
        rating: 4.2,
        sp: 2219,
        mrp: 5999,
        discount: 63,
        desc: {
            details: "A pair of round toe tan flat brogue boots ,has regular styling, has lace-ups detail",
            material: "Upper material: Leather. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Regular Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-brogues',
        image: '/images/product_p27.jpg',
        company: 'Provogue',
        product: 'Men Brown Solid Formal Brogues',
        rating: 4.2,
        sp: 899,
        mrp: 4495,
        discount: 63,
        desc: {
            details: "A pair of brown solid round-toed formal Brogues , has has central lace-ups",
            material: "Faux leather. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Brogues",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-derbys',
        image: '/images/product_p28.jpg',
        company: 'Red Tape',
        product: 'Men Black Solid Leather Formal Derbys',
        rating: 4.1,
        sp: 2039,
        mrp: 6799,
        discount: 70,
        desc: {
            details: "A pair of black solid round toe formal derbys with regular styling has a lace-up closure",
            material: "Leather. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Derbys",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "45 days",
        }
    },
    {
        type: 'men-derbys',
        image: '/images/product_p29.jpg',
        company: 'Bata',
        product: 'Men Tan Brown Textured Formal Derbys',
        rating: 3.8,
        sp: 1999,
        mrp: 3999,
        discount: 50,
        desc: {
            details: "A pair of tan brown textured round-toed formal derbys, with regular styling has a lace-up closure",
            material: "PU. Wipe with clean and dry cloth to remove dust",
            specsType: "Derbys",
            specsToe: "Round Toe",
            specsPattern: "Textured",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-derbys',
        image: '/images/product_p30.jpg',
        company: 'Walke',
        product: 'Men Coffee Brown Solid Formal Derbys',
        rating: 4.3,
        sp: 2599,
        mrp: 4999,
        discount: 50,
        desc: {
            details: "A pair of coffee brown solid round-toed formal derbys, with regular styling has a lace-up closure",
            material: "PU. Wipe with clean and dry cloth to remove dust",
            specsType: "Derbys",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-oxfords',
        image: '/images/product_p31.jpg',
        company: 'INVICTUS',
        product: 'Men Black Formal Textured Oxford Shoes',
        rating: 4,
        sp: 958,
        mrp: 2995,
        discount: 68,
        desc: {
            details: "A pair of Black Textured Oxford Shoes with lace-up detailings",
            material: "PU. Wipe with clean and dry cloth to remove dust",
            specsType: "Oxfords",
            specsToe: "Round Toe",
            specsPattern: "Textured",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-oxfords',
        image: '/images/product_p32.jpg',
        company: 'Arrow',
        product: 'Men Tan Brown Solid Leather Oxford Shoes',
        rating: 3.8,
        sp: 4764,
        mrp: 5499,
        discount: 15,
        desc: {
            details: "A pair of tan brown oxford shoes with central lace-ups",
            material: "Leather. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Oxfords",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-oxfords',
        image: '/images/product_p33.jpg',
        company: 'LOUIS STITCH',
        product: 'Men Brown Leather Formal Oxford Shoes',
        rating: 4.5,
        sp: 2029,
        mrp: 6999,
        discount: 70,
        desc: {
            details: "A pair of brown oxford shoes with central lace-ups",
            material: "Leather. Clean and polish with LOUIS STITCH range of shoe care accessories",
            specsType: "Oxfords",
            specsToe: "Round Toe",
            specsPattern: "Textured",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-monks',
        image: '/images/product_p34.jpg',
        company: 'Sir Corbett',
        product: 'Men Chocolate Brown Formal Monk Shoes',
        rating: 4.1,
        sp: 1098,
        mrp: 3429,
        discount: 70,
        desc: {
            details: "A pair of chocolate brown formal shoes with buckle closure",
            material: "Synthetic. Wipe with a clean, dry cloth when required",
            specsType: "Monk Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Buckle",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-monks',
        image: '/images/product_p35.jpg',
        company: 'Alberto Torresi',
        product: 'Men Brown Formal Monk Shoes',
        rating: 4,
        sp: 1599,
        mrp: 2079,
        discount: 30,
        desc: {
            details: "A pair of brown formal shoes with buckle closure",
            material: "Synthetic. Wipe with a clean, dry cloth when required",
            specsType: "Monk Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Buckle",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'men-monks',
        image: '/images/product_p36.jpg',
        company: 'INVICTUS',
        product: 'Men Black Faux Leather Formal Monk Shoes',
        rating: 4,
        sp: 922,
        mrp: 4195,
        discount: 78,
        desc: {
            details: "A pair of black round-toed formal monk shoes, has regular styling",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Monk Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-ankle',
        image: '/images/product_p37.jpg',
        company: 'Woakers',
        product: 'Men Tan Brown Solid Synthetic High Ankle Flat Boots',
        rating: 4.3,
        sp: 753,
        mrp: 3425,
        discount: 78,
        desc: {
            details: "A pair of brown round-toed ankle boots, has regular styling",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-ankle',
        image: '/images/product_p38.jpg',
        company: 'FAUSTO',
        product: 'Men Tan Brown Mid-Top Leather Flat Ankle Boots',
        rating: 3,
        sp: 1609,
        mrp: 2299,
        discount: 30,
        desc: {
            details: "A pair of round toe tan flat boots ,has regular styling, lace-ups detail",
            material: "Leather. Use a branded leather conditioner to clean the product. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-ankle',
        image: '/images/product_p39.jpg',
        company: 'Alberto Torresi',
        product: 'Men Black High-Top Leather Ankle Boots',
        rating: 4.3,
        sp: 1499,
        mrp: 2999,
        discount: 50,
        desc: {
            details: "A pair of round toe black ankle boots ,has regular styling, lace-ups detail",
            material: "Leather. Use a branded leather conditioner to clean the product. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-ankle',
        image: '/images/product_p40.jpg',
        company: 'Unistar',
        product: 'Men Green High-Top Leather Ankle Boots',
        rating: 4.1,
        sp: 1361,
        mrp: 3240,
        discount: 42,
        desc: {
            details: "A pair of round toe green ankle boots ,has regular styling, lace-ups detail",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'women-ankle',
        image: '/images/product_p79.jpg',
        company: 'M&S',
        product: 'Women Leather Kitten Heel Pointed Ankle Boots',
        rating: 3.2,
        sp: 3136,
        mrp: 3690,
        discount: 15,
        desc: {
            details: "A pair of round toe black ankle boots ,has regular styling, slip-on detail",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "5 months",
        }
    },
    {
        type: 'women-ankle',
        image: '/images/product_p80.jpg',
        company: 'Mango',
        product: 'Women Silver Solid Ankle Boots',
        rating: 3.5,
        sp: 1299,
        mrp: 4330,
        discount: 70,
        desc: {
            details: "A pair of round toe silver solid ankle boots ,has regular styling, slip-on detail",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'women-ankle',
        image: '/images/product_p81.jpg',
        company: 'Kady',
        product: 'Leather Casual Stylish Look Boots Shoes Boots For Women (Pink)',
        rating: 4.2,
        sp: 1995,
        mrp: 3990,
        discount: 50,
        desc: {
            details: "A pair of round toe pink solid ankle boots ,has regular styling, lace-up detail",
            material: "Synthetic. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Ankle Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'men-hiking',
        image: '/images/product_p41.jpg',
        company: 'Bacca Bucci',
        product: 'Men Black Leather Hiking Boots',
        rating: 4.2,
        sp: 2219,
        mrp: 5999,
        discount: 63,
        desc: {
            details: "A pair of square toe black trekking shoes ,has regular styling, lace-ups detail",
            material: "Leather. Use a branded leather conditioner to clean the product. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Trekkking Shoes",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-hiking',
        image: '/images/product_p42.jpg',
        company: 'Decathlon',
        product: 'Men Brown TREKKING Waterproof Hiking Boots',
        rating: 4.4,
        sp: 4999,
        mrp: 9999,
        discount: 50,
        desc: {
            details: "These waterproof boots let you progress on easy trails with good support and walking comfort. Trekking enthusiasts will love these comfortable and lightweight hiking boots, designed to guarantee excellent foot motion. Perfect for treks on easy trails!",
            material: "Outer sole of : 60.0% Thermoplastic Polyurethane, Outer sole of : 40.0% Polyurethane Upper of : 50.0% Polyester, Upper of : 40.0% Leather - Bovine, Upper of : 10.0% Polyurethane Lining and sock of : 100.0% Polyester. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Trekkking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "TPU",
            specsWarranty: "2 years",
        }
    },
    {
        type: 'men-hiking',
        image: '/images/product_p43.jpg',
        company: 'Eego Italy',
        product: 'Men Black Canvas High-Top Camouflage Hiking Boots',
        rating: 4.2,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of black trekking sports shoes, has high-top styling, lace-up detail",
            material: "Canvas. Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Trekkking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Up",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "30 days",
        }
    },
    {
        type: 'men-football',
        image: '/images/product_p46.jpg',
        company: 'Nike',
        product: 'Unisex White & Orange Web Printed Predator Edge.3 FG Football Shoes',
        rating: 4.3,
        sp: 6999,
        mrp: 7999,
        discount: 13,
        desc: {
            details: " White, orange and blue web printed predator edge.3 fg football shoes",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Football Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'men-football',
        image: '/images/product_p48.jpg',
        company: 'Puma',
        product: 'Men TACTO II FG Football Shoes',
        rating: 4.8,
        sp: 3399,
        mrp: 3999,
        discount: 15,
        desc: {
            details: "A pair of black shoes, has regular Styling, lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Football Shoes",
            specsToe: "Round Toe",
            specsPattern: "Marking",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'men-football',
        image: '/images/product_p49.jpg',
        company: 'Adidas',
        product: 'Unisex Coffee Brown Web Printed Predator Edge3 LL FG Football Shoes',
        rating: 4.7,
        sp: 6999,
        mrp: 7999,
        discount: 13,
        desc: {
            details: "A pair of coffee brown shoes, has regular Styling, lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Football Shoes",
            specsToe: "Round Toe",
            specsPattern: "Marking",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'men-golf',
        image: '/images/product_p50.jpg',
        company: 'Nike',
        product: 'Unisex Black Golf Shoes',
        rating: 4.1,
        sp: 4999,
        mrp: 5999,
        discount: 17,
        desc: {
            details: "A pair of black shoes, has regular Styling, lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Golf Shoes",
            specsToe: "Round Toe",
            specsPattern: "Marking",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'men-golf',
        image: '/images/product_p51.jpg',
        company: 'Evergreen Golf',
        product: 'Unisex Grey Golf Shoes',
        rating: 4,
        sp: 3999,
        mrp: 4999,
        discount: 25,
        desc: {
            details: "A pair of grey shoes, has regular Styling, lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Golf Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'men-golf',
        image: '/images/product_p52.jpg',
        company: 'Puma',
        product: 'Unisex White Golf Shoes',
        rating: 4,
        sp: 3599,
        mrp: 4999,
        discount: 28,
        desc: {
            details: "A pair of white shoes, has regular Styling, lace-ups detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Golf Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'men-cycling',
        image: '/images/product_p53.jpg',
        company: 'MTB',
        product: 'Unisex Black Cycling Shoes',
        rating: 4,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of white shoes, has regular Styling, strap-on detail",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Cycling Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'men-cycling',
        image: '/images/product_p54.jpg',
        company: 'Triathlon',
        product: 'Unisex Red Cycling Shoes',
        rating: 4.3,
        sp: 1199,
        mrp: 1999,
        discount: 40,
        desc: {
            details: "A pair of red shoes, has regular Styling, strap-on detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Cycling Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'women-mary-janes',
        image: '/images/product_p63.jpg',
        company: 'Theater',
        product: 'Black Mary Janes Platform Shoes',
        rating: 4.3,
        sp: 1999,
        mrp: 2990,
        discount: 33,
        desc: {
            details: "A pair of black mary jane shoes, has regular Styling, strap-on detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Mary Jane Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "8 months"
        }
    },
    {
        type: 'women-mary-janes',
        image: '/images/product_p64.jpg',
        company: 'YK',
        product: 'Black Mary Janes Heel Shoes',
        rating: 4.4,
        sp: 1599,
        mrp: 3999,
        discount: 60,
        desc: {
            details: "A pair of black mary jane heel shoes, has regular Styling, buckle detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Mary Jane Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Buckle",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months"
        }
    },
    {
        type: 'women-mary-janes',
        image: '/images/product_p65.jpg',
        company: 'Theatre',
        product: 'White Mary Jane Shoes',
        rating: 4.6,
        sp: 1299,
        mrp: 2599,
        discount: 50,
        desc: {
            details: "A pair of white mary jane heel shoes, has regular Styling, buckle detail",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Mary Jane Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Buckle",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'women-knee',
        image: '/images/product_p66.jpg',
        company: 'ZAPATOZ',
        product: 'Women Black Over The Knee Boots',
        rating: 4.2,
        sp: 3299,
        mrp: 5999,
        discount: 45,
        desc: {
            details: "A pair of black solid round toe boots, has high-top styling and lace-ups detail",
            material: "Suede. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Over The Knee Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'women-knee',
        image: '/images/product_p67.png',
        company: 'Roadster',
        product: 'Women Tan Brown High Top Knee Boots',
        rating: 4.3,
        sp: 3599,
        mrp: 5599,
        discount: 36,
        desc: {
            details: "A pair of tan brown solid round toe boots, has high-top styling and lace-ups detail",
            material: "Suede. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Over The Knee Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'women-knee',
        image: '/images/product_p68.jpg',
        company: 'H&M',
        product: 'Women Solid Black Mid Top Knee Boots',
        rating: 4.1,
        sp: 1599,
        mrp: 2599,
        discount: 38,
        desc: {
            details: "A pair of black solid round toe boots, has high-top styling and lace-ups detail",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Over The Knee Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "7 months"
        }
    },
    {
        type: 'women-juttis',
        image: '/images/product_p69.jpg',
        company: 'Natty Feet',
        product: 'Women Naveli Punjabi Juttis',
        rating: 4.4,
        sp: 796,
        mrp: 2490,
        discount: 68,
        desc: {
            details: "A pair of brown coffee naveli punjabi jutti, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Juttis",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month"
        }
    },
    {
        type: 'women-juttis',
        image: '/images/product_p70.jpeg',
        company: 'Handicrafts',
        product: 'Women Ethnic Blue Embroidered Juttis',
        rating: 4.1,
        sp: 899,
        mrp: 1999,
        discount: 55,
        desc: {
            details: "A pair of blue embroidered juttis, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Juttis",
            specsToe: "Open Toe",
            specsPattern: "Embroidered",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months"
        }
    },
    {
        type: 'women-juttis',
        image: '/images/product_p71.jpg',
        company: 'Krafto Jodhpur',
        product: 'Women Pink Thread Flowers Handcrafted Rajasthani Leather Juttis',
        rating: 3.7,
        sp: 699,
        mrp: 3495,
        discount: 80,
        desc: {
            details: "A pair of pink thread flowers handcrafted rajasthani leather juttis, has regular styling and slip-on details",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Juttis",
            specsToe: "Open Toe",
            specsPattern: "Thread Flowers",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'women-juttis',
        image: '/images/product_p72.jpg',
        company: 'Purely Lush',
        product: 'Women Tan Brown Leather Juttis',
        rating: 3.9,
        sp: 799,
        mrp: 1299,
        discount: 38,
        desc: {
            details: "A pair of tan brown leather juttis, has regular styling and slip-on details",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Juttis",
            specsToe: "Open Toe",
            specsPattern: "Waves",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month"
        }
    },
    {
        type: 'women-wellington',
        image: '/images/product_p73.jpg',
        company: 'MadM Direct',
        product: 'Hunter Womens Original Classic Tall Matt Wellington Boots Black Grape',
        rating: 4.2,
        sp: 899,
        mrp: 4499,
        discount: 80,
        desc: {
            details: "A pair of classic tall matt black grape wellington boots, has regular styling and slip-on details",
            material: "Rubber. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Wellington Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'women-wellington',
        image: '/images/product_p74.jpg',
        company: 'Hunter',
        product: 'Womens Tall Matt Wellington Boots Red',
        rating: 4.1,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of classic tall red matt wellington boots, has regular styling and slip-on details",
            material: "Rubber. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Wellington Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'women-moccasins',
        image: '/images/product_p84.jpg',
        company: 'Khadims',
        product: 'Cream Synthetic Women Moccasin',
        rating: 4.2,
        sp: 1410,
        mrp: 3526,
        discount: 40,
        desc: {
            details: "A pair of cream synthetic women moccasins, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Moccasin Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'women-moccasins',
        image: '/images/product_p85.jpg',
        company: 'Julke',
        product: 'Velvet Red Synthetic Women Moccasin',
        rating: 4.4,
        sp: 2799,
        mrp: 3999,
        discount: 30,
        desc: {
            details: "A pair of velvet red synthetic women moccasins, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Moccasin Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "6 months"
        }
    },
    {
        type: 'women-moccasins',
        image: '/images/product_p86.jpg',
        company: 'Hermes',
        product: 'Pink Synthetic Women Moccasin',
        rating: 4.6,
        sp: 1099,
        mrp: 1599,
        discount: 31,
        desc: {
            details: "A pair of pink synthetic women moccasins, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Moccasin Shoes",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "1 month"
        }
    },
    {
        type: 'women-kolhapuris',
        image: '/images/product_p87.jpg',
        company: 'Khadim',
        product: 'Handcrafted Women Kolhapuri Sandals',
        rating: 4.8,
        sp: 889,
        mrp: 1199,
        discount: 26,
        desc: {
            details: "A pair of brown leather women kolhapuri sandals, has regular styling and slip-on details",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Kolhapuri Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "1 month"
        }
    },
    {
        type: 'women-kolhapuris',
        image: '/images/product_p88.jpg',
        company: 'Bata',
        product: 'Women Pink Kolhapuri Shoes',
        rating: 4.5,
        sp: 749,
        mrp: 999,
        discount: 25,
        desc: {
            details: "A pair of pink synthetic women kolhapuri shoes, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Kolhapuri Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "15 days"
        }
    },
    {
        type: 'women-kolhapuris',
        image: '/images/product_p89.jpg',
        company: 'Korakari',
        product: 'Women Olive Green Kolhapuri Shoes',
        rating: 4.2,
        sp: 949,
        mrp: 1199,
        discount: 21,
        desc: {
            details: "A pair of olive green leather women kolhapuri shoes, has regular styling and slip-on details",
            material: "Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Kolhapuri Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p90.jpg',
        company: 'H&M',
        product: 'Women Pink Kitten Heels',
        rating: 4.4,
        sp: 1049,
        mrp: 2499,
        discount: 40,
        desc: {
            details: "A pair of pink kitten heels, has regular styling and strap-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Kitten Heels",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p91.jpg',
        company: 'Marc Loire',
        product: 'Women Black Matte Block Heels',
        rating: 4.7,
        sp: 1199,
        mrp: 2999,
        discount: 26,
        desc: {
            details: "A pair of matte black block heels, has regular styling and strap-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Block Heels",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p92.jpg',
        company: 'Stupmary',
        product: 'Women Black High Platform Heels',
        rating: 4.1,
        sp: 2199,
        mrp: 4999,
        discount: 56,
        desc: {
            details: "A pair of black high platform heels, has regular styling and strap-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Platform Heels",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "4 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p93.jpg',
        company: 'Marc Loire',
        product: 'Women Black Peep Toe Heels',
        rating: 4.3,
        sp: 2239,
        mrp: 5999,
        discount: 63,
        desc: {
            details: "A pair of black peep toe heels, has regular styling and strap-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Peep Toe Heels",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Strap-On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "2 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p94.jpg',
        company: 'Boc',
        product: 'Women Turquoise Wedge Heels',
        rating: 4.1,
        sp: 1123,
        mrp: 2999,
        discount: 63,
        desc: {
            details: "A pair of turquoise wedge heels, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Wedge Heels",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "5 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p95.jpg',
        company: 'Ajanta',
        product: 'Women Red Stiletto Heels',
        rating: 3.9,
        sp: 2199,
        mrp: 3999,
        discount: 45,
        desc: {
            details: "A pair of red stiletto heels, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Wedge Heels",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "5 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p96.jpg',
        company: 'Bata',
        product: 'Women Blue Spool Heels',
        rating: 4.8,
        sp: 889,
        mrp: 1199,
        discount: 26,
        desc: {
            details: "A pair of blue spool heels, has regular styling and lace-up details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Spool Heels",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "3 months"
        }
    },
    {
        type: 'women-heels',
        image: '/images/product_p97.jpg',
        company: 'Levantina',
        product: 'Women Maroon Cone Heels',
        rating: 4.1,
        sp: 999,
        mrp: 1999,
        discount: 50,
        desc: {
            details: "A pair of maroon cone heels, has regular styling and slip-on details",
            material: "Synthetic. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Cone Heels",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "PU",
            specsWarranty: "4 months"
        }
    }
];

export default products;
